IOT_Management/IOT_Management/Controllers/CategoryDevicesController.cs
using Service.Model;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class CategoryDevicesController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: CategoryDevices
        public ActionResult Index()
        {
            return View(db.CategoryDevices.ToList());
        }

        public ActionResult GetAll()
        {
            var all = db.CategoryDevices.ToList();
            return PartialView("_CategoryDeviceMenu", all);
        }

        // GET: CategoryDevices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryDevice categoryDevice = db.CategoryDevices.Find(id);
            if (categoryDevice == null)
            {
                return HttpNotFound();
            }
            return View(categoryDevice);
        }

        // GET: CategoryDevices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryDevices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,ImageUrl")] CategoryDevice categoryDevice)
        {
            if (ModelState.IsValid)
            {
                db.CategoryDevices.Add(categoryDevice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoryDevice);
        }

        // GET: CategoryDevices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryDevice categoryDevice = db.CategoryDevices.Find(id);
            if (categoryDevice == null)
            {
                return HttpNotFound();
            }
            return View(categoryDevice);
        }

        // POST: CategoryDevices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,ImageUrl")] CategoryDevice categoryDevice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoryDevice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoryDevice);
        }

        // GET: CategoryDevices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryDevice categoryDevice = db.CategoryDevices.Find(id);
            if (categoryDevice == null)
            {
                return HttpNotFound();
            }
            return View(categoryDevice);
        }

        // POST: CategoryDevices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoryDevice categoryDevice = db.CategoryDevices.Find(id);
            db.CategoryDevices.Remove(categoryDevice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IOT_Management/IOT_Management/Controllers/NewsController.cs
using Service.Model;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: News
        public ActionResult Index()
        {
            var news = db.News.Include(x => x.CategoryNew);
            return View(news.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name");
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PostId,Title,Short_Desciption,Post_Content,UrlSlug,Published,ViewCount,RateCount,TotalRate,Post_On,Modified,CategoryNewId")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(@new);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PostId,Title,Short_Desciption,Post_Content,UrlSlug,Published,ViewCount,RateCount,TotalRate,Post_On,Modified,CategoryNewId")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@new).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            New @new = db.News.Find(id);
            db.News.Remove(@new);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GetNewsByCategory(int categoryId)
        {
            var news = db.News.Where(x => x.CategoryNewId == categoryId).ToList();
            return View("Index", news);
        }

        public ActionResult GetLastestNews()
        {
            var news = db.News.OrderByDescending(x => x.Post_On).Take(5).ToList();
            return PartialView("_LastestNews", news);
        }
    }
}

IOT_Management/IOT_Management/Views/Shared/LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/login.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

IOT_Management/IOT_Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!--

    TemplateMo 546 Sixteen Clothing

    https://templatemo.com/tm-546-sixteen-clothing

    -->
    <!-- Additional CSS Files -->
    <link href="~/Assets/assets/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Assets/assets/css/templatemo-sixteen.css" rel="stylesheet" />
    <link href="~/Assets/assets/css/owl.css" rel="stylesheet" />
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    @Html.Partial("_PartialHeader")
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <!-- Banner Ends Here -->
    <div style="padding-top:100px">
        @RenderBody()
    </div>



    @Html.Partial("_PartialFooter")

    <!-- Bootstrap core JavaScript -->

    <script src="~/Assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Additional Scripts -->
    <script src="~/Assets/assets/js/custom.js"></script>
    <script src="~/Assets/assets/js/owl.js"></script>
    <script src="~/Assets/assets/js/slick.js"></script>
    <script src="~/Assets/assets/js/isotope.js"></script>
    <script src="~/Assets/assets/js/accordions.js"></script>

    <script>
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            items: 1,
            loop: true,
            margin: 10,
            autoplay: true,
            autoplayTimeout: 2000,
            autoplayHoverPause: false
        });
        $('.play').on('click', function () {
            owl.trigger('play.owl.autoplay', [1000])
        })
        $('.stop').on('click', function () {
            owl.trigger('stop.owl.autoplay')
        })

    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

IOT_Management/IOT_Management/Views/Shared/_PartialBanner.cshtml
<div class="banner header-text">
    <div class="owl-banner owl-carousel">
        <div class="banner-item-01">
            <div class="text-content">
                <h2>Tư duy là sức mạnh của sáng tạo</h2>
            </div>
        </div>
        <div class="banner-item-02">
            <div class="text-content">
                <h2>Tư duy là sức mạnh của sáng tạo</h2>
            </div>
        </div>
        <div class="banner-item-03">
            <div class="text-content">
                <h2>Tư duy là sức mạnh của sáng tạo</h2>
            </div>
        </div>
    </div>
</div>

IOT_Management/IOT_Management/Views/Shared/_PartialFooter.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="inner-content">
                    <p>
                        Copyright &copy; 2020 Sixteen Clothing Co., Ltd.

                        - Design: <a rel="nofollow noopener" href="https://templatemo.com" target="_blank">TemplateMo</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

IOT_Management/IOT_Management/Views/Shared/_PartialHeader.cshtml
<header class="">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="index.html">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link  dropdown-toggle" href="#" data-bs-toggle="dropdown"> Danh mục thiết bị</a>
                        <ul class="dropdown-menu">
                            @Html.Action("GetAll","CategoryDevices")
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "News")">Tin tức phòng ban</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact Us</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"> Tài khoản</a>
                        <ul class="dropdown-menu">
                            @Html.Partial("_LoginPartial")
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>