IOT_Management/IOT_Management/Areas/Admin/Controllers/OutMemberBorrowsController.cs
using OfficeOpenXml;
using OfficeOpenXml.Table;
using Service.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IOT_Management.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OutMemberBorrowsController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();
        // GET: Admin/OutMemberBorrow
        public ActionResult Index()
        {
            var borrowDetail = db.OutMemberBorrows.Include("Device");
            return View(borrowDetail.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.DeviceId = new SelectList(db.Devices, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id, StudentID, StudentName, Phone, Email, TotalBorrow, DeviceId")] OutMemberBorrow outMemberBorrow)
        {
            if (ModelState.IsValid)
            {
                Device device = db.Devices.Find(outMemberBorrow.DeviceId);
                device.TotalRest = device.TotalRest - outMemberBorrow.TotalBorrow;
                if (device.TotalRest < 0)
                {
                    device.TotalRest = 0;
                }

                outMemberBorrow.Device = device;
                outMemberBorrow.StartDate = DateTime.Now;
                db.OutMemberBorrows.Add(outMemberBorrow);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(outMemberBorrow);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutMemberBorrow borrowDetail = db.OutMemberBorrows.Find(id);
            if (borrowDetail == null)
            {
                return HttpNotFound();
            }
            return View(borrowDetail);
        }

        public ActionResult ReturnDevice(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutMemberBorrow borrowDetail = db.OutMemberBorrows.Find(id);
            if (borrowDetail == null)
            {
                return HttpNotFound();
            }
            borrowDetail.IsReturn = true;
            borrowDetail.EndDate = DateTime.Now;

            Device device = db.Devices.Find(borrowDetail.DeviceId);
            device.TotalRest += borrowDetail.TotalBorrow;
            if (device.TotalRest > device.TotalNumber)
            {
                device.TotalRest = device.TotalNumber;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void Export()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage(new FileInfo("MyWorkbook.xlsx")))
            {
                List<OutMemberBorrow> listBorrowDetail = db.OutMemberBorrows.ToList();

                DataTable dt = new DataTable();
                dt.Columns.Add("Id", typeof(int));
                dt.Columns.Add("Device", typeof(string));
                dt.Columns.Add("UserID", typeof(string));
                dt.Columns.Add("UserName", typeof(string));
                dt.Columns.Add("TotalBorrow", typeof(int));
                dt.Columns.Add("StartDate", typeof(string));
                dt.Columns.Add("EndDate", typeof(string));
                dt.Columns.Add("IsReturn", typeof(string));
                foreach (var item in listBorrowDetail)
                {
                    DataRow dr = dt.NewRow();
                    dr[0] = item.Id;
                    dr[1] = item.Device.Name;
                    dr[2] = item.StudentID;
                    dr[3] = item.StudentName;
                    dr[4] = item.TotalBorrow;
                    dr[5] = item.StartDate.ToString("dd/MM/yyyy");
                    dr[6] = item.EndDate.HasValue?item.EndDate.Value.ToString("dd/MM/yyyy"):null;
                    dr[7] = item.IsReturn.ToString();
                    dt.Rows.Add(dr);
                }
                ExcelPackage excel = new ExcelPackage();
                var workSheet = excel.Workbook.Worksheets.Add("Sheet1");
                workSheet.Cells[1, 1].LoadFromDataTable(dt, true, TableStyles.None);
                using (var memoryStream = new MemoryStream())
                {
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment; filename=BorrowDetail.xlsx");
                    excel.SaveAs(memoryStream); memoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }
        }
    }
}

IOT_Management/IOT_Management/Areas/Admin/Views/OutMemberBorrows/Create.cshtml
@model Service.Model.OutMemberBorrow

@{
    ViewBag.Title = "Mượn thiết bị";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>OutMemberBorrow</h4>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <p>Thiết bị</p>
        <div class="col-md-10">
            @Html.DropDownList("DeviceId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p>Số lượng mượn</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalBorrow, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalBorrow, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p>Mã sinh viên</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p>Tên sinh viên</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p>Số điện thoại</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p>Email</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IOT_Management/IOT_Management/Areas/Admin/Views/OutMemberBorrows/Details.cshtml
@model Service.Model.OutMemberBorrow

@{
    ViewBag.Title = "Chi tiết người mượn";
}

<h2>@ViewBag.Title</h2>

<div>
    <dl class="dl-horizontal">


        <dt>
            <p> Mã sinh viên </p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentID)
        </dd>

        <dt>
            <p> Tên sinh viên </p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <dt>
            <p> Số điện thoại</p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            <p> Email </p>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay lại", "Index")
</p>

IOT_Management/IOT_Management/Areas/Admin/Views/OutMemberBorrows/Index.cshtml
@model IEnumerable<Service.Model.OutMemberBorrow>

@{
    ViewBag.Title = "Danh sách mượn thiết bị";
}

<h2>@ViewBag.Title</h2>

<div class="d-inline">
    @Html.ActionLink("Mượn thiết bị", "Create", null, new { @class="float-left"})
    @Html.ActionLink("Xuất ra file excel", "Export", null, new { @class = "float-right" })
</div>
<table class="table">
    <tr>
        <th>
            Tên thiết bị
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Mã sinh viên
        </th>      
        <th>
            Ngày mượn
        </th>
        <th>
            Ngày trả
        </th>
        <th class="text-center">
            Đã trả
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Device.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TotalBorrow)
    </td>
    <td>
        <a href="@Url.Action("Details","OutMemberBorrows",new { id=item.Id})">@item.StudentID</a>
    </td>    
    <td>
        @Html.DisplayFor(modelItem => item.StartDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EndDate)
    </td>
    <td class="text-center">
        @Html.DisplayFor(modelItem => item.IsReturn)
    </td>
    <td>
        @if (!item.IsReturn)
        {
            @Html.ActionLink("Trả thiết bị", "ReturnDevice", new { id = item.Id })
        }
    </td>
</tr>
}

</table>