IOT_Management/IOT_Management/Controllers/BorrowDetailsController.cs
using Microsoft.AspNet.Identity;
using Service.Model;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class BorrowDetailsController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: BorrowDetails
        [Authorize]
        [HttpPost]
        public JsonResult Borrow(int deviceId, int totalBorrow, string startDate, string endDate)
        {
            Device device = db.Devices.Find(deviceId);
            device.TotalRest = device.TotalRest - totalBorrow;
            if(device.TotalRest < 0)
            {
                device.TotalRest = 0;
            }
            BorrowDetail borrowDetail = new BorrowDetail()
            {
                Device = device,
                DeviceId = deviceId,
                Start_Date = DateTime.Parse(startDate),
                End_Date = DateTime.Parse(endDate),
                TotalBorrow = totalBorrow,
                UserId = User.Identity.GetUserId()
        };
            db.BorrowDetails.Add(borrowDetail);
          
            return Json(db.SaveChanges() > 0);
        }

        
    }
}

IOT_Management/IOT_Management/Controllers/CategoryNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Service.Model;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class CategoryNewsController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: CategoryNews
        public ActionResult Index()
        {
            return View(db.CategoryNews.ToList());
        }

        public ActionResult GetAllCategoryNew()
        {
            var categories = db.CategoryNews.ToList();
            return PartialView("_CategoriesNewMenu",categories);
        }

        // GET: CategoryNews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryNew categoryNew = db.CategoryNews.Find(id);
            if (categoryNew == null)
            {
                return HttpNotFound();
            }
            return View(categoryNew);
        }

        // GET: CategoryNews/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Desciption,ImageUrl,ImageName")] CategoryNew categoryNew)
        {
            if (ModelState.IsValid)
            {
                db.CategoryNews.Add(categoryNew);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoryNew);
        }

        // GET: CategoryNews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryNew categoryNew = db.CategoryNews.Find(id);
            if (categoryNew == null)
            {
                return HttpNotFound();
            }
            return View(categoryNew);
        }

        // POST: CategoryNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Desciption,ImageUrl,ImageName")] CategoryNew categoryNew)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoryNew).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoryNew);
        }

        // GET: CategoryNews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryNew categoryNew = db.CategoryNews.Find(id);
            if (categoryNew == null)
            {
                return HttpNotFound();
            }
            return View(categoryNew);
        }

        // POST: CategoryNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CategoryNew categoryNew = db.CategoryNews.Find(id);
            db.CategoryNews.Remove(categoryNew);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IOT_Management/IOT_Management/Controllers/DevicesController.cs
using Service.Model;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class DevicesController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: Devices
        public ActionResult Index()
        {
            var devices = db.Devices.Include(d => d.CategoryDevice);
            return View(devices.ToList());
        }

        public ActionResult GetDevicesByCategory(string CategoryName)
        {
            var devices = db.Devices.Where(x => x.CategoryDevice.Name.Contains(CategoryName));
            return View( "Index",devices);
        }

        // GET: Devices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            ViewBag.CategoryDeviceId = new SelectList(db.CategoryDevices, "Id", "Name");
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,TotalNumber,TotalBorrow,CompanyName,Date_Import,Modified,CategoryDeviceId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryDeviceId = new SelectList(db.CategoryDevices, "Id", "Name", device.CategoryDeviceId);
            return View(device);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryDeviceId = new SelectList(db.CategoryDevices, "Id", "Name", device.CategoryDeviceId);
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,TotalNumber,TotalBorrow,CompanyName,Date_Import,Modified,CategoryDeviceId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryDeviceId = new SelectList(db.CategoryDevices, "Id", "Name", device.CategoryDeviceId);
            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IOT_Management/IOT_Management/Controllers/NewsController.cs
using Service.Model;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IOT_Management.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private ManagementLabContext db = new ManagementLabContext();

        // GET: News
        public ActionResult Index()
        {
            var news = db.News.Include(x => x.CategoryNew);
            return View(news.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name");
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PostId,Title,Short_Desciption,Post_Content,UrlSlug,Published,ViewCount,RateCount,TotalRate,Post_On,Modified,CategoryNewId")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(@new);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PostId,Title,Short_Desciption,Post_Content,UrlSlug,Published,ViewCount,RateCount,TotalRate,Post_On,Modified,CategoryNewId")] New @new)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@new).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryNewId = new SelectList(db.CategoryNews, "Id", "Name", @new.CategoryNewId);
            return View(@new);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            New @new = db.News.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            New @new = db.News.Find(id);
            db.News.Remove(@new);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GetNewsByCategory(int categoryId)
        {
            var news = db.News.Where(x => x.CategoryNewId == categoryId).ToList();
            return View("Index", news);
        }

        public ActionResult GetLastestNews()
        {
            var news = db.News.OrderByDescending(x => x.Post_On).Take(5).ToList();
            return PartialView("_LastestNews", news);
        }
    }
}

IOT_Management/IOT_Management/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Devices Management</title>

    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    @Styles.Render("~/bundles/admincss")

    
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Devices Management</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","CategoryDevices")">
                    <i class="fas fa-hashtag"></i>
                    <span>Loại Thiết Bị</span>
                </a>
            </li>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-laptop-medical"></i>
                    <span>Danh Sách Thiết Bị</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Devices")">Tất cả</a>
                        @Html.Action("GetAll", "CategoryDevices")
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-newspaper"></i>
                    <span>Tin Tức Phòng Ban</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","News")">Tất cả</a>
                        @Html.Action("GetAllCategoryNew", "CategoryNews")
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","TimelineEvents")">
                    <i class="fas fa-fw fa-calendar"></i>
                    <span>Xếp Lịch</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","BorrowDetails")">
                    <i class="fas fa-history"></i>
                    <span>Lịch sử mượn</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","OutMemberBorrows")">
                    <i class="fas fa-history"></i>
                    <span>Mượn thiết bị</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown">
                            <button class="btn btn-secondary dropdown-toggle"type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                            @Html.Partial("_LoginPartial")
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/adminjs")
    @RenderSection("Scripts", false)
</body>

</html>